<?php

/**
 * @file
 * Implements the stage flow functionality required to create and display an entity.
 *
 * This example does not use the
 * @link http://drupal.org/project/entity Entity API module @endlink, which is
 * used by many entity implementations and is recommended by many.
 *
 * An example of use of creating and managing entities using the Entity API
 * module is provided in the
 * @link http://drupal.org/project/model Model Entity module @endlink.
 *
 * @todo: Reference the ronald_istos article series
 * @todo: Reference the Drupal module development book
 * @todo: Add a single field
 */

/**
 * @defgroup stage_flow Example: Entity
 * @ingroup examples
 * @{
 * Example creating a core Entity API entity.
 *
 * Note that this example does not use or demonstrate the contrib Entity API,
 * which you can find here: http://drupal.org/project/entity
 */

/**
 * Implements hook_entity_info().
 *
 * This is the fundamental description of the entity.
 *
 * It provides a single entity with a single bundle and without revision
 * support.
 */
function stage_flow_entity_info() {
  $info['stage_flow'] = array(
    // A human readable label to identify our entity.
    'label' => t('Stage Flow Entity'),

    // The controller for our Entity, extending the Drupal core controller.
    'controller class' => 'StageFlowController',

    // The table for this entity defined in hook_schema()
    'base table' => 'stage_flow',

    // Returns the uri elements of an entity.
    'uri callback' => 'stage_flow_uri',

    // IF fieldable == FALSE, we can't attach fields.
    'fieldable' => TRUE,

    // entity_keys tells the controller what database fields are used for key
    // functions. It is not required if we don't have bundles or revisions.
    // Here we do not support a revision, so that entity key is omitted.
    'entity keys' => array(
      // The 'id' (sid here) is the unique id.
      'id' => 'sid' ,
      // Bundle will be determined by the 'bundle_type' field.
      'bundle' => 'bundle_type',
      'label' => 'label',
    ),
    'bundle keys' => array(
      'bundle' => 'bundle_type',
    ),

    // FALSE disables caching. Caching functionality is handled by Drupal core.
    'static cache' => TRUE,

    // Bundles are alternative groups of fields or configuration
    // associated with a base entity type.
    'bundles' => array(
      'stage_flow_bundle' => array(
        'label' => 'Stage Flow',
        // 'admin' key is used by the Field UI to provide field and
        // display UI pages.
        'admin' => array(
          'path' => 'admin/content/stage-flow/manage',
          'access arguments' => array('administer stage flow entities'),
        ),
      ),
    ),
    // View modes allow entities to be displayed differently based on context.
    // As a demonstration we'll support "Tweaky", but we could have and support
    // multiple display modes.
    'view modes' => array(
      'tweaky' => array(
        'label' => t('Tweaky'),
        'custom settings' => FALSE,
      ),
    ),
  );

  return $info;
}

/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the model types via a hook to avoid a recursion
 * issue as loading the model types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function stage_flow_entity_info_alter(&$entity_info) {
  dpm($entity_info);
  /*
  foreach (model_get_types() as $type => $info) {
    $entity_info['stage_flow']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/model_types/manage/%model_type',
        'real path' => 'admin/structure/model_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer model types'),
      ),
    );
  }
  */ 
}

/**
 * Fetch a stage flow object.
 *
 * This function ends up being a shim between the menu system and
 * stage_flow_load_multiple().
 *
 * This function gets its name from the menu system's wildcard
 * naming conventions. For example, /path/%wildcard would end
 * up calling wildcard_load(%wildcard value). In our case defining
 * the path: stage-flow/%stage_flow in
 * hook_menu() tells Drupal to call stage_flow_load().
 *
 * @param int $sid
 *   Integer specifying the stage flow entity id.
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return object
 *   A fully-loaded $basic object or FALSE if it cannot be loaded.
 *
 * @see stage_flow_load_multiple()
 * @see stage_flow_menu()
 */
function stage_flow_load($sid = NULL, $reset = FALSE) {
  $sids = (isset($sid) ? array($sid) : array());
  $basic = stage_flow_load_multiple($sids, array(), $reset);
  return $basic ? reset($basic) : FALSE;
}

/**
 * Loads multiple stage flow entities.
 *
 * We only need to pass this request along to entity_load(), which
 * will in turn call the load() method of our entity controller class.
 */
function stage_flow_load_multiple($sids = FALSE, $conditions = array(), $reset = FALSE) {
  return entity_load('stage_flow', $sids, $conditions, $reset);
}

/**
 * Implements the uri callback.
 */
function stage_flow_uri($basic) {
  return array(
    'path' => 'stage-flow/' . $basic->sid,
  );
}

/**
 * Implements hook_menu().
 */
function stage_flow_menu() {
  $items['stage-flow'] = array(
    'title' => 'Stage Flow',
    'page callback' => 'stage_flow_info_page',
    'access arguments' => array('view any stage_flow entity'),
  );

  // This provides a place for Field API to hang its own
  // interface and has to be the same as what was defined
  // in basic_entity_info() above.
  $items['admin/content/stage-flow/manage'] = array(
    'title' => 'Stage Flow',
    'page callback' => 'stage_flow_list_entities',
    'access arguments' => array('administer stage flow entities'),
    'type' => MENU_LOCAL_TASK,
  );

  // Add Stage flow entities.
  $items['admin/content/stage-flow/manage/add'] = array(
    'title' => 'Add an Stage Flow Entity',
    'page callback' => 'stage_flow_add',
    'access arguments' => array('create stage flow entities'),
    'type' => MENU_LOCAL_ACTION,
  );

  // List of all stage_flow entities.
  $items['admin/content/stage-flow/manage/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // The page to view our entities - needs to follow what
  // is defined in basic_uri and will use load_basic to retrieve
  // the necessary entity info.
  $items['stage-flow/%stage_flow'] = array(
    'title callback' => 'stage_flow_title',
    'title arguments' => array(1),
    'page callback' => 'stage_flow_view',
    'page arguments' => array(1),
    'access arguments' => array('view any stage_flow entity'),
  );

  // 'View' tab for an individual entity page.
  $items['stage-flow/%stage_flow/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  // 'Edit' tab for an individual entity page.
  $items['stage-flow/%stage_flow/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stage_flow_entity_form', 1),
    'access arguments' => array('edit any stage_flow entity'),
    'type' => MENU_LOCAL_TASK,
  );

  // Add Stage flow entities.
  $items['stage-flow/add'] = array(
    'title' => 'Add an Stage Flow Entity Entity',
    'page callback' => 'stage_flow_add',
    'access arguments' => array('create stage flow entities'),
  );

  return $items;
}

/**
 * Basic information for the page.
 */
function stage_flow_info_page() {
  $content['preface'] = array(
    '#type' => 'item',
    '#markup' => t('The entity example provides a simple Stage flow entity.'),
  );
  if (user_access('administer stage flow entities')) {
    $content['preface']['#markup'] = t('You can administer these and add fields and change the view !link.',
      array('!link' => l(t('here'), 'admin/content/stage-flow/manage'))
    );
  }
  $content['table'] = stage_flow_list_entities();

  return $content;
}

/**
 * Implements hook_permission().
 */
function stage_flow_permission() {
  $permissions = array(
    'administer stage flow entities' => array(
      'title' => t('Administer stage flow entities'),
    ),
    'view any stage_flow entity' => array(
      'title' => t('View any Stage Flow Entity entity'),
    ),
    'edit any stage_flow entity' => array(
      'title' => t('Edit any Stage Flow entity'),
    ),
    'create stage flow entities' => array(
      'title' => t('Create Stage Flow Entity Entities'),
    ),
  );
  return $permissions;
}

/**
 * Returns a render array with all stage_flow entities.
 *
 * In this stage flow example we know that there won't be many entities,
 * so we'll just load them all for display. See pager_example.module
 * to implement a pager. Most implementations would probably do this
 * with the contrib Entity API module, or a view using views module,
 * but we avoid using non-core features in the Examples project.
 *
 * @see pager_example.module
 */
function stage_flow_list_entities() {
  $content = array();
  // Load all of our entities.
  $entities = stage_flow_load_multiple();
  if (!empty($entities)) {
    foreach ($entities as $entity) {
      // Create tabular rows for our entities.
      $rows[] = array(
        'data' => array(
          'id' => $entity->sid,
          'label' => l($entity->label, 'stage-flow/' . $entity->sid),
          'bundle' => $entity->bundle_type,
          'action' => l('Edit', 'stage-flow/' . $entity->sid . '/edit',array('query' => drupal_get_destination())),
        ),
      );
    }
    // Put our entities into a themed table. See theme_table() for details.
    $content['entity_table'] = array(
      '#theme' => 'table',
      '#rows' => $rows,
      '#header' => array(t('ID'), t('Label'), t('Bundle'),t('Action')),
    );
  }
  else {
    // There were no entities. Tell the user.
    $content[] = array(
      '#type' => 'item',
      '#markup' => t('No stage_flow entities currently exist.'),
    );
  }
  return $content;
}

/**
 * Callback for a page title when this entity is displayed.
 */
function stage_flow_title($entity) {
  return t(check_plain($entity->label));
}

/**
 * Menu callback to display an entity.
 *
 * As we load the entity for display, we're responsible for invoking a number
 * of hooks in their proper order.
 *
 * @see hook_entity_prepare_view()
 * @see hook_entity_view()
 * @see hook_entity_view_alter()
 */
function stage_flow_view($entity, $view_mode = 'tweaky') {
  // Our entity type, for convenience.
  $entity_type = 'stage_flow';
  // Start setting up the content.
  $entity->content = array(
    '#view_mode' => $view_mode,
  );
  // Build fields content - this is where the Field API really comes in to play.
  // The task has very little code here because it all gets taken care of by
  // field module.
  // field_attach_prepare_view() lets the fields load any data they need
  // before viewing.
  field_attach_prepare_view($entity_type, array($entity->sid => $entity),
    $view_mode);
  // We call entity_prepare_view() so it can invoke hook_entity_prepare_view()
  // for us.
  entity_prepare_view($entity_type, array($entity->sid => $entity));
  // Now field_attach_view() generates the content for the fields.
  $entity->content += field_attach_view($entity_type, $entity, $view_mode);

  // OK, Field API done, now we can set up some of our own data.
  $entity->content['created'] = array(
    '#type' => 'item',
    '#title' => t('Created date'),
    '#markup' => format_date($entity->created),
  );
  $entity->content['label'] = array(
    '#type' => 'item',
    '#title' => t('Label'),
    '#markup' => $entity->label,
  );

  // Now to invoke some hooks. We need the language code for
  // hook_entity_view(), so let's get that.
  global $language;
  $langcode = $language->language;
  // And now invoke hook_entity_view().
  module_invoke_all('entity_view', $entity, $entity_type, $view_mode,
    $langcode);
  // Now invoke hook_entity_view_alter().
  drupal_alter(array('stage_flow_view', 'entity_view'),
    $entity->content, $entity_type);

  // And finally return the content.
  return $entity->content;
}

/**
 * Implements hook_field_extra_fields().
 *
 * This exposes the "extra fields" (usually properties that can be configured
 * as if they were fields) of the entity as pseudo-fields
 * so that they get handled by the Entity and Field core functionality.
 * Node titles get treated in a similar manner.
 */
function stage_flow_field_extra_fields() {
  $form_elements['label'] = array(
    'label' => t('Label'),
    'description' => t('Label (an extra form field)'),
    'weight' => -5,
  );
  $display_elements['created'] = array(
    'label' => t('Creation date'),
    'description' => t('Creation date (an extra display field)'),
    'weight' => 0,
  );
  $display_elements['label'] = array(
    'label' => t('Label'),
    'description' => t('Just like title, but trying to point out that it is a separate property'),
    'weight' => 0,
  );

  // Since we have only one bundle type, we'll just provide the extra_fields
  // for it here.
  $extra_fields['stage_flow']['stage_flow_bundle']['form'] = $form_elements;
  $extra_fields['stage_flow']['stage_flow_bundle']['display'] = $display_elements;

  return $extra_fields;
}

/**
 * Provides a wrapper on the edit form to add a new entity.
 */
function stage_flow_add() {
  // Create a stage flow entity structure to be used and passed to the validation
  // and submission functions.
  $entity = entity_get_controller('stage_flow')->create();
  return drupal_get_form('stage_flow_entity_form', $entity);
}

/**
 * Form function to create an stage_flow entity.
 *
 * The pattern is:
 * - Set up the form for the data that is specific to your
 *   entity: the columns of your base table.
 * - Call on the Field API to pull in the form elements
 *   for fields attached to the entity.
 */
function stage_flow_entity_form($form, &$form_state, $entity) {
  $form['label'] = array(
    '#type' => 'textfield',
    '#title' => t('Label'),
    '#required' => TRUE,
    '#default_value' => $entity->label,
  );

  $form['basic_entity'] = array(
    '#type' => 'value',
    '#value' => $entity,
  );

  field_attach_form('stage_flow', $entity, $form, $form_state);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 100,
  );
  $form['delete'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
    '#submit' => array('stage_flow_edit_delete'),
    '#weight' => 200,
  );

  return $form;
}


/**
 * Validation handler for stage_flow_add_form form.
 *
 * We pass things straight through to the Field API to handle validation
 * of the attached fields.
 */
function stage_flow_entity_form_validate($form, &$form_state) {
  field_attach_form_validate('stage_flow', $form_state['values']['basic_entity'], $form, $form_state);
}


/**
 * Form submit handler: Submits basic_add_form information.
 */
function stage_flow_entity_form_submit($form, &$form_state) {
  $entity = $form_state['values']['basic_entity'];
  $entity->label = $form_state['values']['label'];
  field_attach_submit('stage_flow', $entity, $form, $form_state);
  $entity = stage_flow_save($entity);
  $form_state['redirect'] = 'stage-flow/' . $entity->sid;
  //$form_state['redirect'] = current_path(); //drupal_get_destination();
}

/**
 * Form deletion handler.
 *
 * @todo: 'Are you sure?' message.
 */
function stage_flow_edit_delete($form, &$form_state) {
  $entity = $form_state['values']['basic_entity'];
  stage_flow_delete($entity);
  drupal_set_message(t('The entity %label (ID %id) has been deleted',
    array('%label' => $entity->label, '%id' => $entity->sid))
  );
  $form_state['redirect'] = 'stage-flow';
}

/**
 * We save the entity by calling the controller.
 */
function stage_flow_save(&$entity) {
  return entity_get_controller('stage_flow')->save($entity);
}

/**
 * Use the controller to delete the entity.
 */
function stage_flow_delete($entity) {
  entity_get_controller('stage_flow')->delete($entity);
}

/**
 * StageFlowControllerInterface definition.
 *
 * We create an interface here because anyone could come along and
 * use hook_entity_info_alter() to change our controller class.
 * We want to let them know what methods our class needs in order
 * to function with the rest of the module, so here's a handy list.
 *
 * @see hook_entity_info_alter()
 */
interface StageFlowControllerInterface
  extends DrupalEntityControllerInterface {

  /**
   * Create an entity.
   */
  public function create();

  /**
   * Save an entity.
   *
   * @param object $entity
   *   The entity to save.
   */
  public function save($entity);

  /**
   * Delete an entity.
   *
   * @param object $entity
   *   The entity to delete.
   */
  public function delete($entity);

}

/**
 * StageFlowController extends DrupalDefaultEntityController.
 *
 * Our subclass of DrupalDefaultEntityController lets us add a few
 * important create, update, and delete methods.
 */
class StageFlowController
  extends DrupalDefaultEntityController
  implements StageFlowControllerInterface {

  /**
   * Create and return a new stage_flow entity.
   */
  public function create() {
    $entity = new stdClass();
    $entity->type = 'stage_flow';
    $entity->sid = 0;
    $entity->bundle_type = 'stage_flow_bundle';
    $entity->label = '';
    return $entity;
  }

  /**
   * Saves the custom fields using drupal_write_record().
   */
  public function save($entity) {
    // If our entity has no sid, then we need to give it a
    // time of creation.
    if (empty($entity->sid)) {
      $entity->created = REQUEST_TIME;
    }
    // Invoke hook_entity_presave().
    module_invoke_all('entity_presave', $entity, 'stage_flow');
    // The 'primary_keys' argument determines whether this will be an insert
    // or an update. So if the entity already has an ID, we'll specify
    // sid as the key.
    $primary_keys = $entity->sid ? 'sid' : array();
    // Write out the entity record.
    drupal_write_record('stage_flow', $entity, $primary_keys);
    // We're going to invoke either hook_entity_update() or
    // hook_entity_insert(), depending on whether or not this is a
    // new entity. We'll just store the name of hook_entity_insert()
    // and change it if we need to.
    $invocation = 'entity_insert';
    // Now we need to either insert or update the fields which are
    // attached to this entity. We use the same primary_keys logic
    // to determine whether to update or insert, and which hook we
    // need to invoke.
    if (empty($primary_keys)) {
      field_attach_insert('stage_flow', $entity);
    }
    else {
      field_attach_update('stage_flow', $entity);
      $invocation = 'entity_update';
    }
    // Invoke either hook_entity_update() or hook_entity_insert().
    module_invoke_all($invocation, $entity, 'stage_flow');
    return $entity;
  }

  /**
   * Delete a single entity.
   *
   * Really a convenience function for deleteMultiple().
   */
  public function delete($entity) {
    $this->deleteMultiple(array($entity));
  }

  /**
   * Delete one or more stage_flow entities.
   *
   * Deletion is unfortunately not supported in the base
   * DrupalDefaultEntityController class.
   *
   * @param array $entities
   *   An array of entity IDs or a single numeric ID.
   */
  public function deleteMultiple($entities) {
    $sids = array();
    if (!empty($entities)) {
      $transaction = db_transaction();
      try {
        foreach ($entities as $entity) {
          // Invoke hook_entity_delete().
          module_invoke_all('entity_delete', $entity, 'stage_flow');
          field_attach_delete('stage_flow', $entity);
          $sids[] = $entity->sid;
        }
        db_delete('stage_flow')
          ->condition('sid', $sids, 'IN')
          ->execute();
      }
      catch (Exception $e) {
        $transaction->rollback();
        watchdog_exception('stage_flow', $e);
        throw $e;
      }
    }
  }
}

/**
 * @} End of "defgroup stage_flow".
 */
